version: '3'
services:
  # myapplication:
  #   image: myapp:1.0
  #   environment:
  #     - MONGODB_CONNSTRING=mongodb://DockerDiamond:MongoDBhunter24365fd@10.10.10.26
  #   ports:
  #     - 3000:3000
  mongodb:
    image: mongo:5.0
    network_mode: "host"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=DockerDiamond
      - MONGO_INITDB_ROOT_PASSWORD=MongoDBhunter24365fd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=10.10.10.26
      - ME_CONFIG_MONGODB_ADMINUSERNAME=DockerDiamond
      - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoDBhunter24365fd
