version: '3'
services:

  frontend:
    build: ./client
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    restart: always

  backend:
    build: ./server
    environment:
      - PORT=5000
      - CONNECTION_URL=mongodb://DockerDiamond:MongoDBhunter24365fd@mongodb
    ports:
      - 5000:5000
    restart: always

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=DockerDiamond
      - MONGO_INITDB_ROOT_PASSWORD=MongoDBhunter24365fd
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=DockerDiamond
      - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoDBhunter24365fd
    restart: always
